<?php

namespace Database\Seeders;

use App\Models\Soal;
use App\Models\Surat;
use App\Models\Quiz;
use App\Models\Juz;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class SoalSeeder extends Seeder
{
    /**
     * Dataset soal Juz 30 (melanjutkan ayat, mengisi ayat kosong, pengetahuan surat).
     * - surat_id di-resolve dinamis dari tabel `surats` berdasarkan kolom `nomor_surat`.
     * - jawaban_benar berisi huruf opsi yang benar: a/b/c/d.
     * - file_audio sengaja dikosongkan (null).
     * - Semua soal di sini otomatis dikaitkan ke Quiz "Juz 30" (juz_id = 30),
     *   supaya badge "Penjelajah Juz 30" bisa langsung berfungsi tanpa
     *   perlu setup manual lewat Tinker.
     */
    public function run(): void
    {
        $now = Carbon::now();
        $surahMap = Surat::pluck('id', 'nomor_surat')->toArray();

        // ── Siapkan Quiz "Juz 30" ──────────────────────────────────────────────
        $juz30 = Juz::where('nomor', 30)->first();

        if (!$juz30) {
            throw new \RuntimeException("Juz dengan nomor=30 belum ada di tabel `juz`. Jalankan JuzSeeder terlebih dahulu.");
        }

        $quiz = Quiz::updateOrCreate(
            ['title' => 'Quiz Juz 30'],
            [
                'juz_id'        => $juz30->id,
                'is_active'     => true,
                'duration'      => 30,
                'order'         => 1, // quiz pertama, sesuai urutan hafalan dari Juz 30
                'attempt_limit' => 0,
                'passing_score' => 100,
                'bobot_poin'    => 1.00,
            ]
        );

        $data = [
            [
                'nomor_surat_ref' => 78,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah An-Naba ayat 21):
"إِنَّ جَهَنَّمَ كَانَتْ مِرْصَادًا"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'لِّلطَّٰغِينَ مَـَٔابًا',
                'opsi_b' => 'وَكَوَاعِبَ أَتْرَابًا',
                'opsi_c' => 'وَجَعَلْنَا نَوْمَكُمْ سُبَاتًا',
                'opsi_d' => 'ثُمَّ كَلَّا سَيَعْلَمُونَ',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 79,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah An-Naziat ayat 26):
"إِنَّ فِى ذَٰلِكَ لَعِبْرَةً لِّمَن يَخْشَىٰٓ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'فَإِذَا جَآءَتِ ٱلطَّآمَّةُ ٱلْكُبْرَىٰ',
                'opsi_b' => 'ءَأَنتُمْ أَشَدُّ خَلْقًا أَمِ ٱلسَّمَآءُ بَنَىٰهَا',
                'opsi_c' => 'تَتْبَعُهَا ٱلرَّادِفَةُ',
                'opsi_d' => 'وَٱلْجِبَالَ أَرْسَىٰهَا',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 80,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Abasa ayat 5):
"أَمَّا مَنِ ٱسْتَغْنَىٰ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'فَأَنتَ لَهُۥ تَصَدَّىٰ',
                'opsi_b' => 'وَأُمِّهِۦ وَأَبِيهِ',
                'opsi_c' => 'مَّرْفُوعَةٍ مُّطَهَّرَةٍۭ',
                'opsi_d' => 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ عَبَسَ وَتَوَلَّىٰٓ',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 81,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah At-Takwir ayat 12):
"وَإِذَا ٱلْجَحِيمُ سُعِّرَتْ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'إِنَّهُۥ لَقَوْلُ رَسُولٍ كَرِيمٍ',
                'opsi_b' => 'ٱلْجَوَارِ ٱلْكُنَّسِ',
                'opsi_c' => 'وَإِذَا ٱلْجَنَّةُ أُزْلِفَتْ',
                'opsi_d' => 'وَٱلصُّبْحِ إِذَا تَنَفَّسَ',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 82,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Al-Infitar ayat 17):
"وَمَآ أَدْرَىٰكَ مَا يَوْمُ ٱلدِّينِ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'كِرَامًا كَٰتِبِينَ',
                'opsi_b' => 'ٱلَّذِى خَلَقَكَ فَسَوَّىٰكَ فَعَدَلَكَ',
                'opsi_c' => 'ثُمَّ مَآ أَدْرَىٰكَ مَا يَوْمُ ٱلدِّينِ',
                'opsi_d' => 'يَٰٓأَيُّهَا ٱلْإِنسَٰنُ مَا غَرَّكَ بِرَبِّكَ ٱلْكَرِيمِ',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 83,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Al-Mutaffifin ayat 3):
"وَإِذَا كَالُوهُمْ أَو وَّزَنُوهُمْ يُخْسِرُونَ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'ثُمَّ يُقَالُ هَٰذَا ٱلَّذِى كُنتُم بِهِۦ تُكَذِّبُونَ',
                'opsi_b' => 'كَلَّآ إِنَّ كِتَٰبَ ٱلْأَبْرَارِ لَفِى عِلِّيِّينَ',
                'opsi_c' => 'كَلَّآ إِنَّهُمْ عَن رَّبِّهِمْ يَوْمَئِذٍ لَّمَحْجُوبُونَ',
                'opsi_d' => 'أَلَا يَظُنُّ أُو۟لَٰٓئِكَ أَنَّهُم مَّبْعُوثُونَ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 84,
                'pertanyaan' => 'Ayat berikut adalah lanjutan dari ayat sebelumnya. Sebutkan ayat SEBELUM ayat ini (Surah Al-Inshiqaq ayat 15):
"بَلَىٰٓ إِنَّ رَبَّهُۥ كَانَ بِهِۦ بَصِيرًا"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'فَبَشِّرْهُم بِعَذَابٍ أَلِيمٍ',
                'opsi_b' => 'إِنَّهُۥ ظَنَّ أَن لَّن يَحُورَ',
                'opsi_c' => 'وَٱلَّيْلِ وَمَا وَسَقَ',
                'opsi_d' => 'فَسَوْفَ يُحَاسَبُ حِسَابًا يَسِيرًا',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 85,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Al-Buruj ayat 3):
"وَشَاهِدٍ وَمَشْهُودٍ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'وَهُمْ عَلَىٰ مَا يَفْعَلُونَ بِٱلْمُؤْمِنِينَ شُهُودٌ',
                'opsi_b' => 'إِنَّ ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّٰلِحَٰتِ لَهُمْ جَنَّٰتٌ تَجْرِى مِن تَحْتِهَا ٱلْأَنْهَٰرُ ذَٰلِكَ ٱلْفَوْزُ ٱلْكَبِيرُ',
                'opsi_c' => 'إِذْ هُمْ عَلَيْهَا قُعُودٌ',
                'opsi_d' => 'قُتِلَ أَصْحَٰبُ ٱلْأُخْدُودِ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 86,
                'pertanyaan' => 'Ayat berikut adalah lanjutan dari ayat sebelumnya. Sebutkan ayat SEBELUM ayat ini (Surah At-Tariq ayat 4):
"إِن كُلُّ نَفْسٍ لَّمَّا عَلَيْهَا حَافِظٌ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'خُلِقَ مِن مَّآءٍ دَافِقٍ',
                'opsi_b' => 'يَوْمَ تُبْلَى ٱلسَّرَآئِرُ',
                'opsi_c' => 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ وَٱلسَّمَآءِ وَٱلطَّارِقِ',
                'opsi_d' => 'ٱلنَّجْمُ ٱلثَّاقِبُ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 87,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Al-Ala ayat 2):
"ٱلَّذِى خَلَقَ فَسَوَّىٰ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'وَنُيَسِّرُكَ لِلْيُسْرَىٰ',
                'opsi_b' => 'وَٱلَّذِى قَدَّرَ فَهَدَىٰ',
                'opsi_c' => 'فَذَكِّرْ إِن نَّفَعَتِ ٱلذِّكْرَىٰ',
                'opsi_d' => 'وَٱلَّذِىٓ أَخْرَجَ ٱلْمَرْعَىٰ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 88,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Al-Ghashiyah ayat 8):
"وُجُوهٌ يَوْمَئِذٍ نَّاعِمَةٌ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'لِّسَعْيِهَا رَاضِيَةٌ',
                'opsi_b' => 'تَصْلَىٰ نَارًا حَامِيَةً',
                'opsi_c' => 'تُسْقَىٰ مِنْ عَيْنٍ ءَانِيَةٍ',
                'opsi_d' => 'إِنَّ إِلَيْنَآ إِيَابَهُمْ',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 89,
                'pertanyaan' => 'Ayat berikut adalah lanjutan dari ayat sebelumnya. Sebutkan ayat SEBELUM ayat ini (Surah Al-Fajr ayat 20):
"وَتُحِبُّونَ ٱلْمَالَ حُبًّا جَمًّا"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'وَٱدْخُلِى جَنَّتِى',
                'opsi_b' => 'وَتَأْكُلُونَ ٱلتُّرَاثَ أَكْلًا لَّمًّا',
                'opsi_c' => 'وَلَيَالٍ عَشْرٍ',
                'opsi_d' => 'وَأَمَّآ إِذَا مَا ٱبْتَلَىٰهُ فَقَدَرَ عَلَيْهِ رِزْقَهُۥ فَيَقُولُ رَبِّىٓ أَهَٰنَنِ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 90,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Al-Balad ayat 2):
"وَأَنتَ حِلٌّۢ بِهَٰذَا ٱلْبَلَدِ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'فَلَا ٱقْتَحَمَ ٱلْعَقَبَةَ',
                'opsi_b' => 'وَوَالِدٍ وَمَا وَلَدَ',
                'opsi_c' => 'وَهَدَيْنَٰهُ ٱلنَّجْدَيْنِ',
                'opsi_d' => 'أَوْ إِطْعَٰمٌ فِى يَوْمٍ ذِى مَسْغَبَةٍ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 91,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Ash-Shams ayat 1):
"بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ وَٱلشَّمْسِ وَضُحَىٰهَا"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'وَقَدْ خَابَ مَن دَسَّىٰهَا',
                'opsi_b' => 'وَٱلسَّمَآءِ وَمَا بَنَىٰهَا',
                'opsi_c' => 'فَقَالَ لَهُمْ رَسُولُ ٱللَّهِ نَاقَةَ ٱللَّهِ وَسُقْيَٰهَا',
                'opsi_d' => 'وَٱلْقَمَرِ إِذَا تَلَىٰهَا',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 92,
                'pertanyaan' => 'Ayat berikut adalah lanjutan dari ayat sebelumnya. Sebutkan ayat SEBELUM ayat ini (Surah Al-Lail ayat 11):
"وَمَا يُغْنِى عَنْهُ مَالُهُۥٓ إِذَا تَرَدَّىٰٓ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ وَٱلَّيْلِ إِذَا يَغْشَىٰ',
                'opsi_b' => 'فَسَنُيَسِّرُهُۥ لِلْعُسْرَىٰ',
                'opsi_c' => 'إِلَّا ٱبْتِغَآءَ وَجْهِ رَبِّهِ ٱلْأَعْلَىٰ',
                'opsi_d' => 'إِنَّ عَلَيْنَا لَلْهُدَىٰ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 93,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Ad-Duha ayat 3):
"مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'فَأَمَّا ٱلْيَتِيمَ فَلَا تَقْهَرْ',
                'opsi_b' => 'وَلَلْءَاخِرَةُ خَيْرٌ لَّكَ مِنَ ٱلْأُولَىٰ',
                'opsi_c' => 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ وَٱلضُّحَىٰ',
                'opsi_d' => 'وَوَجَدَكَ عَآئِلًا فَأَغْنَىٰ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 94,
                'pertanyaan' => 'Ayat berikut adalah lanjutan dari ayat sebelumnya. Sebutkan ayat SEBELUM ayat ini (Surah Ash-Sharh ayat 6):
"إِنَّ مَعَ ٱلْعُسْرِ يُسْرًا"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ أَلَمْ نَشْرَحْ لَكَ صَدْرَكَ',
                'opsi_b' => 'وَرَفَعْنَا لَكَ ذِكْرَكَ',
                'opsi_c' => 'فَإِنَّ مَعَ ٱلْعُسْرِ يُسْرًا',
                'opsi_d' => 'ٱلَّذِىٓ أَنقَضَ ظَهْرَكَ',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 95,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah At-Tin ayat 5):
"ثُمَّ رَدَدْنَٰهُ أَسْفَلَ سَٰفِلِينَ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'أَلَيْسَ ٱللَّهُ بِأَحْكَمِ ٱلْحَٰكِمِينَ',
                'opsi_b' => 'لَقَدْ خَلَقْنَا ٱلْإِنسَٰنَ فِىٓ أَحْسَنِ تَقْوِيمٍ',
                'opsi_c' => 'وَهَٰذَا ٱلْبَلَدِ ٱلْأَمِينِ',
                'opsi_d' => 'إِلَّا ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّٰلِحَٰتِ فَلَهُمْ أَجْرٌ غَيْرُ مَمْنُونٍ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 96,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Al-Alaq ayat 4):
"ٱلَّذِى عَلَّمَ بِٱلْقَلَمِ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'سَنَدْعُ ٱلزَّبَانِيَةَ',
                'opsi_b' => 'عَلَّمَ ٱلْإِنسَٰنَ مَا لَمْ يَعْلَمْ',
                'opsi_c' => 'عَبْدًا إِذَا صَلَّىٰٓ',
                'opsi_d' => 'كَلَّا لَئِن لَّمْ يَنتَهِ لَنَسْفَعًۢا بِٱلنَّاصِيَةِ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 97,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Al-Qadr ayat 3):
"لَيْلَةُ ٱلْقَدْرِ خَيْرٌ مِّنْ أَلْفِ شَهْرٍ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'بِّسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ إِنَّآ أَنزَلْنَٰهُ فِى لَيْلَةِ ٱلْقَدْرِ',
                'opsi_b' => 'سَلَٰمٌ هِىَ حَتَّىٰ مَطْلَعِ ٱلْفَجْرِ',
                'opsi_c' => 'وَمَآ أَدْرَىٰكَ مَا لَيْلَةُ ٱلْقَدْرِ',
                'opsi_d' => 'تَنَزَّلُ ٱلْمَلَٰٓئِكَةُ وَٱلرُّوحُ فِيهَا بِإِذْنِ رَبِّهِم مِّن كُلِّ أَمْرٍ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 98,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Al-Bayinah ayat 5):
"وَمَآ أُمِرُوٓا۟ إِلَّا لِيَعْبُدُوا۟ ٱللَّهَ مُخْلِصِينَ لَهُ ٱلدِّينَ حُنَفَآءَ وَيُقِيمُوا۟ ٱلصَّلَوٰةَ وَيُؤْتُوا۟ ٱلزَّكَوٰةَ وَذَٰلِكَ دِينُ ٱلْقَيِّمَةِ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'إِنَّ ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّٰلِحَٰتِ أُو۟لَٰٓئِكَ هُمْ خَيْرُ ٱلْبَرِيَّةِ',
                'opsi_b' => 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ لَمْ يَكُنِ ٱلَّذِينَ كَفَرُوا۟ مِنْ أَهْلِ ٱلْكِتَٰبِ وَٱلْمُشْرِكِينَ مُنفَكِّينَ حَتَّىٰ تَأْتِيَهُمُ ٱلْبَيِّنَةُ',
                'opsi_c' => 'إِنَّ ٱلَّذِينَ كَفَرُوا۟ مِنْ أَهْلِ ٱلْكِتَٰبِ وَٱلْمُشْرِكِينَ فِى نَارِ جَهَنَّمَ خَٰلِدِينَ فِيهَآ أُو۟لَٰٓئِكَ هُمْ شَرُّ ٱلْبَرِيَّةِ',
                'opsi_d' => 'رَسُولٌ مِّنَ ٱللَّهِ يَتْلُوا۟ صُحُفًا مُّطَهَّرَةً',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 99,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Az-Zalzalah ayat 5):
"بِأَنَّ رَبَّكَ أَوْحَىٰ لَهَا"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'يَوْمَئِذٍ يَصْدُرُ ٱلنَّاسُ أَشْتَاتًا لِّيُرَوْا۟ أَعْمَٰلَهُمْ',
                'opsi_b' => 'يَوْمَئِذٍ تُحَدِّثُ أَخْبَارَهَا',
                'opsi_c' => 'فَمَن يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُۥ',
                'opsi_d' => 'وَأَخْرَجَتِ ٱلْأَرْضُ أَثْقَالَهَا',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 100,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Al-Adiyat ayat 10):
"وَحُصِّلَ مَا فِى ٱلصُّدُورِ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'وَإِنَّهُۥ لِحُبِّ ٱلْخَيْرِ لَشَدِيدٌ',
                'opsi_b' => 'فَٱلْمُورِيَٰتِ قَدْحًا',
                'opsi_c' => 'إِنَّ رَبَّهُم بِهِمْ يَوْمَئِذٍ لَّخَبِيرٌۢ',
                'opsi_d' => 'فَأَثَرْنَ بِهِۦ نَقْعًا',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 101,
                'pertanyaan' => 'Ayat berikut adalah lanjutan dari ayat sebelumnya. Sebutkan ayat SEBELUM ayat ini (Surah Al-Qariah ayat 9):
"فَأُمُّهُۥ هَاوِيَةٌ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'فَأَمَّا مَن ثَقُلَتْ مَوَٰزِينُهُۥ',
                'opsi_b' => 'وَأَمَّا مَنْ خَفَّتْ مَوَٰزِينُهُۥ',
                'opsi_c' => 'وَمَآ أَدْرَىٰكَ مَا هِيَهْ',
                'opsi_d' => 'وَتَكُونُ ٱلْجِبَالُ كَٱلْعِهْنِ ٱلْمَنفُوشِ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 102,
                'pertanyaan' => 'Ayat berikut adalah lanjutan dari ayat sebelumnya. Sebutkan ayat SEBELUM ayat ini (Surah Al-Takathur ayat 8):
"ثُمَّ لَتُسْـَٔلُنَّ يَوْمَئِذٍ عَنِ ٱلنَّعِيمِ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'لَتَرَوُنَّ ٱلْجَحِيمَ',
                'opsi_b' => 'ثُمَّ لَتَرَوُنَّهَا عَيْنَ ٱلْيَقِينِ',
                'opsi_c' => 'كَلَّا لَوْ تَعْلَمُونَ عِلْمَ ٱلْيَقِينِ',
                'opsi_d' => 'كَلَّا سَوْفَ تَعْلَمُونَ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 103,
                'pertanyaan' => 'Ayat berikut adalah lanjutan dari ayat sebelumnya. Sebutkan ayat SEBELUM ayat ini (Surah Al-Asr ayat 3):
"إِلَّا ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّٰلِحَٰتِ وَتَوَاصَوْا۟ بِٱلْحَقِّ وَتَوَاصَوْا۟ بِٱلصَّبْرِ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ وَٱلْعَصْرِ',
                'opsi_b' => 'لَّٰبِثِينَ فِيهَآ أَحْقَابًا',
                'opsi_c' => 'إِنَّ ٱلْإِنسَٰنَ لَفِى خُسْرٍ',
                'opsi_d' => 'إِذْ نَادَىٰهُ رَبُّهُۥ بِٱلْوَادِ ٱلْمُقَدَّسِ طُوًى',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 104,
                'pertanyaan' => 'Ayat berikut adalah lanjutan dari ayat sebelumnya. Sebutkan ayat SEBELUM ayat ini (Surah Al-Humazah ayat 7):
"ٱلَّتِى تَطَّلِعُ عَلَى ٱلْأَفْـِٔدَةِ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'فِى عَمَدٍ مُّمَدَّدَةٍۭ',
                'opsi_b' => 'نَارُ ٱللَّهِ ٱلْمُوقَدَةُ',
                'opsi_c' => 'ٱلَّذِى جَمَعَ مَالًا وَعَدَّدَهُۥ',
                'opsi_d' => 'كَلَّا لَيُنۢبَذَنَّ فِى ٱلْحُطَمَةِ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 105,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Al-Fil ayat 2):
"أَلَمْ يَجْعَلْ كَيْدَهُمْ فِى تَضْلِيلٍ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ أَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِأَصْحَٰبِ ٱلْفِيلِ',
                'opsi_b' => 'تَرْمِيهِم بِحِجَارَةٍ مِّن سِجِّيلٍ',
                'opsi_c' => 'فَجَعَلَهُمْ كَعَصْفٍ مَّأْكُولٍۭ',
                'opsi_d' => 'وَأَرْسَلَ عَلَيْهِمْ طَيْرًا أَبَابِيلَ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 106,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Quraish ayat 3):
"فَلْيَعْبُدُوا۟ رَبَّ هَٰذَا ٱلْبَيْتِ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ لِإِيلَٰفِ قُرَيْشٍ',
                'opsi_b' => 'إِۦلَٰفِهِمْ رِحْلَةَ ٱلشِّتَآءِ وَٱلصَّيْفِ',
                'opsi_c' => 'ٱلَّذِىٓ أَطْعَمَهُم مِّن جُوعٍ وَءَامَنَهُم مِّنْ خَوْفٍۭ',
                'opsi_d' => 'وَأَكْوَابٌ مَّوْضُوعَةٌ',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 107,
                'pertanyaan' => 'Ayat berikut adalah lanjutan dari ayat sebelumnya. Sebutkan ayat SEBELUM ayat ini (Surah Al-Ma\'un ayat 2):
"فَذَٰلِكَ ٱلَّذِى يَدُعُّ ٱلْيَتِيمَ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'ٱلَّذِينَ هُمْ عَن صَلَاتِهِمْ سَاهُونَ',
                'opsi_b' => 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ أَرَءَيْتَ ٱلَّذِى يُكَذِّبُ بِٱلدِّينِ',
                'opsi_c' => 'ٱلَّذِينَ هُمْ يُرَآءُونَ',
                'opsi_d' => 'وَلَا يَحُضُّ عَلَىٰ طَعَامِ ٱلْمِسْكِينِ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 108,
                'pertanyaan' => 'Ayat berikut adalah lanjutan dari ayat sebelumnya. Sebutkan ayat SEBELUM ayat ini (Surah Al-Kauthar ayat 3):
"إِنَّ شَانِئَكَ هُوَ ٱلْأَبْتَرُ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'فَصَلِّ لِرَبِّكَ وَٱنْحَرْ',
                'opsi_b' => 'مَا ٱلْقَارِعَةُ',
                'opsi_c' => 'يَٰٓأَيُّهَا ٱلْإِنسَٰنُ مَا غَرَّكَ بِرَبِّكَ ٱلْكَرِيمِ',
                'opsi_d' => 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ إِنَّآ أَعْطَيْنَٰكَ ٱلْكَوْثَرَ',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 109,
                'pertanyaan' => 'Ayat berikut adalah lanjutan dari ayat sebelumnya. Sebutkan ayat SEBELUM ayat ini (Surah Al-Kafirun ayat 5):
"وَلَآ أَنتُمْ عَٰبِدُونَ مَآ أَعْبُدُ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ قُلْ يَٰٓأَيُّهَا ٱلْكَٰفِرُونَ',
                'opsi_b' => 'لَكُمْ دِينُكُمْ وَلِىَ دِينِ',
                'opsi_c' => 'لَآ أَعْبُدُ مَا تَعْبُدُونَ',
                'opsi_d' => 'وَلَآ أَنَا۠ عَابِدٌ مَّا عَبَدتُّمْ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 110,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah An-Nasr ayat 1):
"بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ إِذَا جَآءَ نَصْرُ ٱللَّهِ وَٱلْفَتْحُ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'إِنَّهُۥ هُوَ يُبْدِئُ وَيُعِيدُ',
                'opsi_b' => 'وَمَا هُوَ بِقَوْلِ شَيْطَٰنٍ رَّجِيمٍ',
                'opsi_c' => 'وَرَأَيْتَ ٱلنَّاسَ يَدْخُلُونَ فِى دِينِ ٱللَّهِ أَفْوَاجًا',
                'opsi_d' => 'فَسَبِّحْ بِحَمْدِ رَبِّكَ وَٱسْتَغْفِرْهُ إِنَّهُۥ كَانَ تَوَّابًۢا',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 111,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Al-Masad ayat 4):
"وَٱمْرَأَتُهُۥ حَمَّالَةَ ٱلْحَطَبِ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'سَيَصْلَىٰ نَارًا ذَاتَ لَهَبٍ',
                'opsi_b' => 'مَآ أَغْنَىٰ عَنْهُ مَالُهُۥ وَمَا كَسَبَ',
                'opsi_c' => 'فِى جِيدِهَا حَبْلٌ مِّن مَّسَدٍۭ',
                'opsi_d' => 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ تَبَّتْ يَدَآ أَبِى لَهَبٍ وَتَبَّ',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 112,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Al-Ikhlas ayat 2):
"ٱللَّهُ ٱلصَّمَدُ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ قُلْ هُوَ ٱللَّهُ أَحَدٌ',
                'opsi_b' => 'لَمْ يَلِدْ وَلَمْ يُولَدْ',
                'opsi_c' => 'مُّطَاعٍ ثَمَّ أَمِينٍ',
                'opsi_d' => 'وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 113,
                'pertanyaan' => 'Ayat berikut adalah lanjutan dari ayat sebelumnya. Sebutkan ayat SEBELUM ayat ini (Surah Al-Falaq ayat 5):
"وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ',
                'opsi_b' => 'مِن شَرِّ مَا خَلَقَ',
                'opsi_c' => 'وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ',
                'opsi_d' => 'وَمِن شَرِّ ٱلنَّفَّٰثَٰتِ فِى ٱلْعُقَدِ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 114,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah An-Nas ayat 1):
"بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'إِلَٰهِ ٱلنَّاسِ',
                'opsi_b' => 'مَلِكِ ٱلنَّاسِ',
                'opsi_c' => 'ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ',
                'opsi_d' => 'مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 79,
                'pertanyaan' => 'Ayat berikut adalah lanjutan dari ayat sebelumnya. Sebutkan ayat SEBELUM ayat ini (Surah An-Naziat ayat 29):
"وَأَغْطَشَ لَيْلَهَا وَأَخْرَجَ ضُحَىٰهَا"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'رَفَعَ سَمْكَهَا فَسَوَّىٰهَا',
                'opsi_b' => 'فَأَخَذَهُ ٱللَّهُ نَكَالَ ٱلْءَاخِرَةِ وَٱلْأُولَىٰٓ',
                'opsi_c' => 'فَقَالَ أَنَا۠ رَبُّكُمُ ٱلْأَعْلَىٰ',
                'opsi_d' => 'إِنَّ فِى ذَٰلِكَ لَعِبْرَةً لِّمَن يَخْشَىٰٓ',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 81,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah At-Takwir ayat 1):
"بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ إِذَا ٱلشَّمْسُ كُوِّرَتْ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'وَمَا تَشَآءُونَ إِلَّآ أَن يَشَآءَ ٱللَّهُ رَبُّ ٱلْعَٰلَمِينَ',
                'opsi_b' => 'وَإِذَا ٱلْجَحِيمُ سُعِّرَتْ',
                'opsi_c' => 'ذِى قُوَّةٍ عِندَ ذِى ٱلْعَرْشِ مَكِينٍ',
                'opsi_d' => 'وَإِذَا ٱلنُّجُومُ ٱنكَدَرَتْ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 94,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Ash-Sharh ayat 7):
"فَإِذَا فَرَغْتَ فَٱنصَبْ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'وَرَفَعْنَا لَكَ ذِكْرَكَ',
                'opsi_b' => 'وَإِلَىٰ رَبِّكَ فَٱرْغَب',
                'opsi_c' => 'وَوَضَعْنَا عَنكَ وِزْرَكَ',
                'opsi_d' => 'ٱلَّذِىٓ أَنقَضَ ظَهْرَكَ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 78,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah An-Naba ayat 18):
"يَوْمَ يُنفَخُ فِى ٱلصُّورِ فَتَأْتُونَ أَفْوَاجًا"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'وَكُلَّ شَىْءٍ أَحْصَيْنَٰهُ كِتَٰبًا',
                'opsi_b' => 'يَوْمَ يَقُومُ ٱلرُّوحُ وَٱلْمَلَٰٓئِكَةُ صَفًّا لَّا يَتَكَلَّمُونَ إِلَّا مَنْ أَذِنَ لَهُ ٱلرَّحْمَٰنُ وَقَالَ صَوَابًا',
                'opsi_c' => 'جَزَآءً وِفَاقًا',
                'opsi_d' => 'وَفُتِحَتِ ٱلسَّمَآءُ فَكَانَتْ أَبْوَٰبًا',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 92,
                'pertanyaan' => 'Lanjutkan ayat berikut ini (Surah Al-Lail ayat 9):
"وَكَذَّبَ بِٱلْحُسْنَىٰ"',
                'jenis' => 'melanjutkan',
                'file_audio' => null,
                'opsi_a' => 'فَسَنُيَسِّرُهُۥ لِلْعُسْرَىٰ',
                'opsi_b' => 'إِنَّ سَعْيَكُمْ لَشَتَّىٰ',
                'opsi_c' => 'وَصَدَّقَ بِٱلْحُسْنَىٰ',
                'opsi_d' => 'فَسَنُيَسِّرُهُۥ لِلْيُسْرَىٰ',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 78,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah An-Naba ayat 25):
"______ حَمِيمًا وَغَسَّاقًا"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'إِلَّا',
                'opsi_b' => 'وَهَّاجًا',
                'opsi_c' => 'يَرَهُۥٓ',
                'opsi_d' => 'سَعَىٰ',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 79,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah An-Naziat ayat 7):
"تَتْبَعُهَا ______"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'كِرَامًا',
                'opsi_b' => 'ٱلرَّادِفَةُ',
                'opsi_c' => 'دَكًّا',
                'opsi_d' => 'شَهْرٍ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 80,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Abasa ayat 16):
"______ بَرَرَةٍ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'رَجْعِهِۦ',
                'opsi_b' => 'كِرَامٍۭ',
                'opsi_c' => 'كَأَنَّهُمْ',
                'opsi_d' => 'حَدَآئِقَ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 81,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah At-Takwir ayat 7):
"وَإِذَا ٱلنُّفُوسُ ______"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'عِلْمَ',
                'opsi_b' => 'زُوِّجَتْ',
                'opsi_c' => 'فَكِهِينَ',
                'opsi_d' => 'خَٰشِعَةٌ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 82,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Infitar ayat 7):
"ٱلَّذِى خَلَقَكَ فَسَوَّىٰكَ ______"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'ٱكْتَالُوا۟',
                'opsi_b' => 'فَعَدَلَكَ',
                'opsi_c' => 'جَآءَ',
                'opsi_d' => 'رَبِّكِ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 83,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Mutaffifin ayat 8):
"______ أَدْرَىٰكَ مَا سِجِّينٌ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'أَزْوَٰجًا',
                'opsi_b' => 'وَمَآ',
                'opsi_c' => 'جَهَنَّمَ',
                'opsi_d' => 'وَٱلْمَلَٰٓئِكَةُ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 84,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Inshiqaq ayat 2):
"______ لِرَبِّهَا وَحُقَّتْ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'رِحْلَةَ',
                'opsi_b' => 'ٱلْفَلَقِ',
                'opsi_c' => 'وَأَذِنَتْ',
                'opsi_d' => 'ٱلْمَبْثُوثِ',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 85,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Buruj ayat 2):
"______ ٱلْمَوْعُودِ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'ثُبُورًا',
                'opsi_b' => 'يَحْيَىٰ',
                'opsi_c' => 'سَعِيرًا',
                'opsi_d' => 'وَٱلْيَوْمِ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 86,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah At-Tariq ayat 3):
"______ ٱلثَّاقِبُ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'ٱلنَّجْمُ',
                'opsi_b' => 'يَقُومُ',
                'opsi_c' => 'فَأَثَرْنَ',
                'opsi_d' => 'وَٱلشَّمْسِ',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 87,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Ala ayat 10):
"سَيَذَّكَّرُ ______ يَخْشَىٰ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'مَن',
                'opsi_b' => 'ٱبْتَلَىٰهُ',
                'opsi_c' => 'ٱلسَّرَآئِرُ',
                'opsi_d' => 'أَهْلِ',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 88,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Ghashiyah ayat 16):
"وَزَرَابِىُّ ______"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'أَغْنَىٰ',
                'opsi_b' => 'مَبْثُوثَةٌ',
                'opsi_c' => 'كَأَنَّهُمْ',
                'opsi_d' => 'أَكْفَرَهُۥ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 89,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Fajr ayat 4):
"______ إِذَا يَسْرِ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'دَافِقٍ',
                'opsi_b' => 'وَأَرْسَلَ',
                'opsi_c' => 'سَفَرَةٍ',
                'opsi_d' => 'وَٱلَّيْلِ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 90,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Balad ayat 5):
"أَيَحْسَبُ أَن لَّن يَقْدِرَ عَلَيْهِ ______"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'لَّسْتَ',
                'opsi_b' => 'أَحَدٌ',
                'opsi_c' => 'ٱلْعَقَبَةَ',
                'opsi_d' => 'ٱلذِّكْرَىٰ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 91,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Ash-Shams ayat 2):
"وَٱلْقَمَرِ ______ تَلَىٰهَا"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'قُلُوبِهِم',
                'opsi_b' => 'ٱلنَّارِ',
                'opsi_c' => 'إِذَا',
                'opsi_d' => 'لَيْلَةِ',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 92,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Lail ayat 21):
"وَلَسَوْفَ ______"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'وَٱلْمَلَٰٓئِكَةُ',
                'opsi_b' => 'يَنظُرُونَ',
                'opsi_c' => 'عِيشَةٍ',
                'opsi_d' => 'يَرْضَىٰ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 93,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Ad-Duha ayat 4):
"وَلَلْءَاخِرَةُ خَيْرٌ لَّكَ مِنَ ______"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'شَرًّا',
                'opsi_b' => 'ٱلْأُولَىٰ',
                'opsi_c' => 'وَمَشْهُودٍ',
                'opsi_d' => 'وَبَنَيْنَا',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 94,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Ash-Sharh ayat 5):
"فَإِنَّ ______ ٱلْعُسْرِ يُسْرًا"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'أَشْتَاتًا',
                'opsi_b' => 'أَهْلِهِۦ',
                'opsi_c' => 'مُخْلِصِينَ',
                'opsi_d' => 'مَعَ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 95,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah At-Tin ayat 6):
"إِلَّا ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّٰلِحَٰتِ فَلَهُمْ ______ غَيْرُ مَمْنُونٍ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'يَصْلَى',
                'opsi_b' => 'أَجْرٌ',
                'opsi_c' => 'جَحِيمٍ',
                'opsi_d' => 'وَٱلَّذِى',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 96,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Alaq ayat 11):
"أَرَءَيْتَ إِن كَانَ ______ ٱلْهُدَىٰٓ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'وَأَخَّرَتْ',
                'opsi_b' => 'وَجَآءَ',
                'opsi_c' => 'لِّيُرَوْا۟',
                'opsi_d' => 'عَلَى',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 97,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Qadr ayat 4):
"تَنَزَّلُ ٱلْمَلَٰٓئِكَةُ وَٱلرُّوحُ فِيهَا ______ رَبِّهِم مِّن كُلِّ أَمْرٍ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'ٱلرَّحِيمِ',
                'opsi_b' => 'بِإِذْنِ',
                'opsi_c' => 'وَقَبَ',
                'opsi_d' => 'ٱلْقُرْءَانُ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 98,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Bayinah ayat 5):
"وَمَآ أُمِرُوٓا۟ إِلَّا لِيَعْبُدُوا۟ ٱللَّهَ مُخْلِصِينَ لَهُ ٱلدِّينَ ______ وَيُقِيمُوا۟ ٱلصَّلَوٰةَ وَيُؤْتُوا۟ ٱلزَّكَوٰةَ وَذَٰلِكَ دِينُ ٱلْقَيِّمَةِ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'عَلَيْنَا',
                'opsi_b' => 'أَثِيمٍ',
                'opsi_c' => 'وَهُوَ',
                'opsi_d' => 'حُنَفَآءَ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 99,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Az-Zalzalah ayat 1):
"______ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ إِذَا زُلْزِلَتِ ٱلْأَرْضُ زِلْزَالَهَا"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'بِسْمِ',
                'opsi_b' => 'بِهَا',
                'opsi_c' => 'أَمْرٍ',
                'opsi_d' => 'فِيمَ',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 100,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Adiyat ayat 6):
"إِنَّ ______ لِرَبِّهِۦ لَكَنُودٌ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'رَّبِّهِمْ',
                'opsi_b' => 'بِأَحْكَمِ',
                'opsi_c' => 'كُفُوًا',
                'opsi_d' => 'ٱلْإِنسَٰنَ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 101,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Qariah ayat 5):
"وَتَكُونُ ٱلْجِبَالُ كَٱلْعِهْنِ ______"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'أَنقَضَ',
                'opsi_b' => 'ٱلْفَوْزُ',
                'opsi_c' => 'ٱلْمَنفُوشِ',
                'opsi_d' => 'أَءِنَّا',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 102,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Takathur ayat 5):
"كَلَّا لَوْ تَعْلَمُونَ عِلْمَ ______"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'ٱسْتَغْنَىٰٓ',
                'opsi_b' => 'تَنسَىٰٓ',
                'opsi_c' => 'ٱلْيَقِينِ',
                'opsi_d' => 'وَٱلَّذِينَ',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 103,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Asr ayat 1):
"بِسْمِ ______ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ وَٱلْعَصْرِ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'ضَبْحًا',
                'opsi_b' => 'مَسْرُورًا',
                'opsi_c' => 'وَأَخَّرَتْ',
                'opsi_d' => 'ٱللَّهِ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 104,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Humazah ayat 6):
"______ ٱللَّهِ ٱلْمُوقَدَةُ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'مَالُهُۥ',
                'opsi_b' => 'ٱلْبَلَدِ',
                'opsi_c' => 'وَمُوسَىٰ',
                'opsi_d' => 'نَارُ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 105,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Fil ayat 3):
"وَأَرْسَلَ ______ طَيْرًا أَبَابِيلَ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'مِهَٰدًا',
                'opsi_b' => 'عَلَيْهِمْ',
                'opsi_c' => 'ٱلنَّاسِ',
                'opsi_d' => 'وَيُقِيمُوا۟',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 106,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Quraish ayat 4):
"ٱلَّذِىٓ أَطْعَمَهُم مِّن جُوعٍ وَءَامَنَهُم مِّنْ ______"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'ٱلْمُطْمَئِنَّةُ',
                'opsi_b' => 'نَّفَعَتِ',
                'opsi_c' => 'خَوْفٍۭ',
                'opsi_d' => 'وَٱلزَّيْتُونِ',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 107,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Ma\'un ayat 7):
"______ ٱلْمَاعُونَ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'مُّحِيطٌۢ',
                'opsi_b' => 'أَذِنَ',
                'opsi_c' => 'مَعَ',
                'opsi_d' => 'وَيَمْنَعُونَ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 108,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Kauthar ayat 2):
"______ لِرَبِّكَ وَٱنْحَرْ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'مُّطَهَّرَةً',
                'opsi_b' => 'فَصَلِّ',
                'opsi_c' => 'حَامِيَةً',
                'opsi_d' => 'وَلَسَوْفَ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 109,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Kafirun ayat 5):
"وَلَآ أَنتُمْ ______ مَآ أَعْبُدُ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'يَرْضَىٰ',
                'opsi_b' => 'عَلَيْهِمُ',
                'opsi_c' => 'ٱلْعَقَبَةَ',
                'opsi_d' => 'عَٰبِدُونَ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 110,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah An-Nasr ayat 3):
"فَسَبِّحْ بِحَمْدِ رَبِّكَ وَٱسْتَغْفِرْهُ ______ كَانَ تَوَّابًۢا"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'ضَاحِكَةٌ',
                'opsi_b' => 'سُئِلَتْ',
                'opsi_c' => 'ٱلْقَيِّمَةِ',
                'opsi_d' => 'إِنَّهُۥ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 111,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Masad ayat 1):
"بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ______ تَبَّتْ يَدَآ أَبِى لَهَبٍ وَتَبَّ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'ٱلرَّحِيمِ',
                'opsi_b' => 'وَفَٰكِهَةً',
                'opsi_c' => 'قَتَرَةٌ',
                'opsi_d' => 'زَجْرَةٌ',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 112,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Ikhlas ayat 4):
"وَلَمْ يَكُن ______ كُفُوًا أَحَدٌۢ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'رَسُولٌ',
                'opsi_b' => 'لَّهُۥ',
                'opsi_c' => 'دَافِقٍ',
                'opsi_d' => 'ٱلزَّبَانِيَةَ',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 113,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Falaq ayat 1):
"بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ قُلْ ______ بِرَبِّ ٱلْفَلَقِ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'يَتَزَكَّىٰ',
                'opsi_b' => 'ٱلْأَعْمَىٰ',
                'opsi_c' => 'جُوعٍ',
                'opsi_d' => 'أَعُوذُ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 114,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah An-Nas ayat 4):
"مِن ______ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'كِذَّابًا',
                'opsi_b' => 'خَابَ',
                'opsi_c' => 'شَرِّ',
                'opsi_d' => 'سَبِّحِ',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 100,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Adiyat ayat 10):
"______ مَا فِى ٱلصُّدُورِ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'جَنَّتِى',
                'opsi_b' => 'بِٱلْحَقِّ',
                'opsi_c' => 'وَأَكِيدُ',
                'opsi_d' => 'وَحُصِّلَ',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 82,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Infitar ayat 18):
"______ مَآ أَدْرَىٰكَ مَا يَوْمُ ٱلدِّينِ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'زِلْزَالَهَا',
                'opsi_b' => 'أَلَّا',
                'opsi_c' => 'ثُمَّ',
                'opsi_d' => 'بِٱلشَّفَقِ',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 83,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Al-Mutaffifin ayat 10):
"______ يَوْمَئِذٍ لِّلْمُكَذِّبِينَ"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'جَنَّٰتٌ',
                'opsi_b' => 'تُجْزَىٰٓ',
                'opsi_c' => 'وَيْلٌ',
                'opsi_d' => 'تَعْرِفُ',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 91,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Ash-Shams ayat 15):
"وَلَا يَخَافُ ______"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'عُقْبَٰهَا',
                'opsi_b' => 'بِٱلسَّاهِرَةِ',
                'opsi_c' => 'لِّلطَّٰغِينَ',
                'opsi_d' => 'لِّنُخْرِجَ',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 91,
                'pertanyaan' => 'Lengkapi bagian yang kosong pada ayat berikut ini (Surah Ash-Shams ayat 6):
"______ وَمَا طَحَىٰهَا"',
                'jenis' => 'mengisi',
                'file_audio' => null,
                'opsi_a' => 'مُّؤْصَدَةٌۢ',
                'opsi_b' => 'وَٱقْتَرِب',
                'opsi_c' => 'وَٱلْأَرْضِ',
                'opsi_d' => 'ٱلصَّلَوٰةَ',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 78,
                'pertanyaan' => 'Apa arti nama Surah An-Naba dalam Bahasa Indonesia?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'Berita Besar',
                'opsi_b' => 'Pengumpat',
                'opsi_c' => 'Subuh',
                'opsi_d' => 'Orang-Orang Curang',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 79,
                'pertanyaan' => 'Surah An-Naziat adalah surah yang ke berapa dalam susunan mushaf Al-Qur\'an?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '79',
                'opsi_b' => '81',
                'opsi_c' => '93',
                'opsi_d' => '92',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 80,
                'pertanyaan' => 'Surah Abasa adalah surah yang ke berapa dalam susunan mushaf Al-Qur\'an?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '85',
                'opsi_b' => '88',
                'opsi_c' => '80',
                'opsi_d' => '87',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 81,
                'pertanyaan' => 'Surah apakah yang letaknya tepat setelah Surah At-Takwir dalam susunan mushaf?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'Al-Infitar',
                'opsi_b' => 'Al-Ikhlas',
                'opsi_c' => 'Al-Kauthar',
                'opsi_d' => 'An-Naziat',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 82,
                'pertanyaan' => 'Ada berapa jumlah ayat dalam Surah Al-Infitar?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '22',
                'opsi_b' => '5',
                'opsi_c' => '19',
                'opsi_d' => '9',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 83,
                'pertanyaan' => 'Surah apakah yang letaknya tepat setelah Surah Al-Mutaffifin dalam susunan mushaf?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'An-Naba',
                'opsi_b' => 'Al-Inshiqaq',
                'opsi_c' => 'Al-Kauthar',
                'opsi_d' => 'Al-Falaq',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 84,
                'pertanyaan' => 'Apa arti nama Surah Al-Inshiqaq dalam Bahasa Indonesia?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'Barang Yang Berguna',
                'opsi_b' => 'Orang-Orang Curang',
                'opsi_c' => 'Pertolongan',
                'opsi_d' => 'Terbelah',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 85,
                'pertanyaan' => 'Surah Al-Buruj adalah surah yang ke berapa dalam susunan mushaf Al-Qur\'an?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '93',
                'opsi_b' => '96',
                'opsi_c' => '108',
                'opsi_d' => '85',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 86,
                'pertanyaan' => 'Ada berapa jumlah ayat dalam Surah At-Tariq?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '11',
                'opsi_b' => '29',
                'opsi_c' => '17',
                'opsi_d' => '20',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 87,
                'pertanyaan' => 'Surah Al-Ala adalah surah yang ke berapa dalam susunan mushaf Al-Qur\'an?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '87',
                'opsi_b' => '78',
                'opsi_c' => '88',
                'opsi_d' => '111',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 88,
                'pertanyaan' => 'Apa arti nama Surah Al-Ghashiyah dalam Bahasa Indonesia?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'Hari Kiamat',
                'opsi_b' => 'Pengumpat',
                'opsi_c' => 'Maha Tinggi',
                'opsi_d' => 'Barang Yang Berguna',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 89,
                'pertanyaan' => 'Apa arti nama Surah Al-Fajr dalam Bahasa Indonesia?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'Penggulungan',
                'opsi_b' => 'Pemberian Yang Banyak',
                'opsi_c' => 'Fajar',
                'opsi_d' => 'Asar',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 90,
                'pertanyaan' => 'Surah apakah yang letaknya tepat setelah Surah Al-Balad dalam susunan mushaf?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'Al-Fajr',
                'opsi_b' => 'Ash-Shams',
                'opsi_c' => 'At-Tariq',
                'opsi_d' => 'Ad-Duha',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 91,
                'pertanyaan' => 'Ada berapa jumlah ayat dalam Surah Ash-Shams?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '15',
                'opsi_b' => '25',
                'opsi_c' => '11',
                'opsi_d' => '29',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 92,
                'pertanyaan' => 'Ada berapa jumlah ayat dalam Surah Al-Lail?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '9',
                'opsi_b' => '21',
                'opsi_c' => '30',
                'opsi_d' => '29',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 93,
                'pertanyaan' => 'Ada berapa jumlah ayat dalam Surah Ad-Duha?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '11',
                'opsi_b' => '5',
                'opsi_c' => '17',
                'opsi_d' => '4',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 94,
                'pertanyaan' => 'Ada berapa jumlah ayat dalam Surah Ash-Sharh?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '26',
                'opsi_b' => '6',
                'opsi_c' => '8',
                'opsi_d' => '42',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 95,
                'pertanyaan' => 'Surah At-Tin adalah surah yang ke berapa dalam susunan mushaf Al-Qur\'an?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '106',
                'opsi_b' => '92',
                'opsi_c' => '95',
                'opsi_d' => '105',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 96,
                'pertanyaan' => 'Surah apakah yang letaknya tepat setelah Surah Al-Alaq dalam susunan mushaf?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'An-Naba',
                'opsi_b' => 'Quraish',
                'opsi_c' => 'Al-Mutaffifin',
                'opsi_d' => 'Al-Qadr',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 97,
                'pertanyaan' => 'Surah apakah yang letaknya tepat setelah Surah Al-Qadr dalam susunan mushaf?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'An-Nasr',
                'opsi_b' => 'At-Tin',
                'opsi_c' => 'Al-Bayinah',
                'opsi_d' => 'At-Tariq',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 98,
                'pertanyaan' => 'Ada berapa jumlah ayat dalam Surah Al-Bayinah?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '8',
                'opsi_b' => '29',
                'opsi_c' => '11',
                'opsi_d' => '20',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 99,
                'pertanyaan' => 'Surah apakah yang letaknya tepat setelah Surah Az-Zalzalah dalam susunan mushaf?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'Al-Ghashiyah',
                'opsi_b' => 'Al-Adiyat',
                'opsi_c' => 'Abasa',
                'opsi_d' => 'Al-Asr',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 100,
                'pertanyaan' => 'Ada berapa jumlah ayat dalam Surah Al-Adiyat?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '15',
                'opsi_b' => '11',
                'opsi_c' => '19',
                'opsi_d' => '30',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 101,
                'pertanyaan' => 'Ada berapa jumlah ayat dalam Surah Al-Qariah?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '5',
                'opsi_b' => '7',
                'opsi_c' => '11',
                'opsi_d' => '15',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 102,
                'pertanyaan' => 'Surah Al-Takathur adalah surah yang ke berapa dalam susunan mushaf Al-Qur\'an?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '111',
                'opsi_b' => '102',
                'opsi_c' => '109',
                'opsi_d' => '103',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 103,
                'pertanyaan' => 'Surah Al-Asr adalah surah yang ke berapa dalam susunan mushaf Al-Qur\'an?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '94',
                'opsi_b' => '103',
                'opsi_c' => '89',
                'opsi_d' => '110',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 104,
                'pertanyaan' => 'Apa arti nama Surah Al-Humazah dalam Bahasa Indonesia?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'Pertolongan',
                'opsi_b' => 'Bukti Nyata',
                'opsi_c' => 'Buah Tin',
                'opsi_d' => 'Pengumpat',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 105,
                'pertanyaan' => 'Ada berapa jumlah ayat dalam Surah Al-Fil?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '5',
                'opsi_b' => '40',
                'opsi_c' => '7',
                'opsi_d' => '46',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 106,
                'pertanyaan' => 'Surah apakah yang letaknya tepat setelah Surah Quraish dalam susunan mushaf?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'Al-Falaq',
                'opsi_b' => 'Al-Ma\'un',
                'opsi_c' => 'An-Naziat',
                'opsi_d' => 'Al-Ikhlas',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 107,
                'pertanyaan' => 'Apa arti nama Surah Al-Ma\'un dalam Bahasa Indonesia?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'Barang Yang Berguna',
                'opsi_b' => 'Gugusan Bintang',
                'opsi_c' => 'Terbelah',
                'opsi_d' => 'Quraisy',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 108,
                'pertanyaan' => 'Surah apakah yang letaknya tepat setelah Surah Al-Kauthar dalam susunan mushaf?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'Al-Lail',
                'opsi_b' => 'Al-Kafirun',
                'opsi_c' => 'Al-Mutaffifin',
                'opsi_d' => 'Al-Fajr',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 109,
                'pertanyaan' => 'Apa arti nama Surah Al-Kafirun dalam Bahasa Indonesia?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'Hari Kiamat',
                'opsi_b' => 'Lapang',
                'opsi_c' => 'Subuh',
                'opsi_d' => 'Orang-Orang kafir',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 110,
                'pertanyaan' => 'Surah An-Nasr adalah surah yang ke berapa dalam susunan mushaf Al-Qur\'an?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '102',
                'opsi_b' => '114',
                'opsi_c' => '110',
                'opsi_d' => '89',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 111,
                'pertanyaan' => 'Apa arti nama Surah Al-Masad dalam Bahasa Indonesia?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'Barang Yang Berguna',
                'opsi_b' => 'Subuh',
                'opsi_c' => 'Terbelah',
                'opsi_d' => 'Api Yang Bergejolak',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 112,
                'pertanyaan' => 'Apa arti nama Surah Al-Ikhlas dalam Bahasa Indonesia?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'Pemberian Yang Banyak',
                'opsi_b' => 'Ikhlas',
                'opsi_c' => 'Malam',
                'opsi_d' => 'Terbelah',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 113,
                'pertanyaan' => 'Apa arti nama Surah Al-Falaq dalam Bahasa Indonesia?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'Fajar',
                'opsi_b' => 'Subuh',
                'opsi_c' => 'Matahari',
                'opsi_d' => 'Quraisy',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 114,
                'pertanyaan' => 'Ada berapa jumlah ayat dalam Surah An-Nas?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '3',
                'opsi_b' => '15',
                'opsi_c' => '46',
                'opsi_d' => '6',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 97,
                'pertanyaan' => 'Ada berapa jumlah ayat dalam Surah Al-Qadr?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '5',
                'opsi_b' => '42',
                'opsi_c' => '8',
                'opsi_d' => '20',
                'jawaban_benar' => 'A',
            ],
            [
                'nomor_surat_ref' => 91,
                'pertanyaan' => 'Apa arti nama Surah Ash-Shams dalam Bahasa Indonesia?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'Segumpal Darah',
                'opsi_b' => 'Malam',
                'opsi_c' => 'Asar',
                'opsi_d' => 'Matahari',
                'jawaban_benar' => 'D',
            ],
            [
                'nomor_surat_ref' => 108,
                'pertanyaan' => 'Apa arti nama Surah Al-Kauthar dalam Bahasa Indonesia?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'Gajah',
                'opsi_b' => 'Api Yang Bergejolak',
                'opsi_c' => 'Pemberian Yang Banyak',
                'opsi_d' => 'Segumpal Darah',
                'jawaban_benar' => 'C',
            ],
            [
                'nomor_surat_ref' => 92,
                'pertanyaan' => 'Surah apakah yang letaknya tepat setelah Surah Al-Lail dalam susunan mushaf?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => 'Al-Buruj',
                'opsi_b' => 'Ad-Duha',
                'opsi_c' => 'At-Tariq',
                'opsi_d' => 'Al-Fil',
                'jawaban_benar' => 'B',
            ],
            [
                'nomor_surat_ref' => 96,
                'pertanyaan' => 'Ada berapa jumlah ayat dalam Surah Al-Alaq?',
                'jenis' => 'pengetahuan',
                'file_audio' => null,
                'opsi_a' => '11',
                'opsi_b' => '26',
                'opsi_c' => '19',
                'opsi_d' => '21',
                'jawaban_benar' => 'C',
            ],
        ];

        // ── Simpan soal & kaitkan ke Quiz Juz 30 ─────────────────────────────
        $order = 1;
        $soalIdsForPivot = [];

        foreach ($data as $row) {
            $nomorSurat = $row['nomor_surat_ref'];
            unset($row['nomor_surat_ref']);

            if (!isset($surahMap[$nomorSurat])) {
                throw new \RuntimeException("Surat dengan nomor_surat={$nomorSurat} belum ada di tabel `surats`. Jalankan SuratSeeder terlebih dahulu.");
            }

            $row['surat_id'] = $surahMap[$nomorSurat];

            $soal = Soal::create($row);

            $soalIdsForPivot[$soal->id] = ['order' => $order];
            $order++;
        }

        // Kaitkan semua soal ke Quiz Juz 30 (sync agar tidak dobel kalau seeder dijalankan ulang)
        $quiz->soals()->syncWithoutDetaching($soalIdsForPivot);
    }
}